grupa_projekt:
    resource: "@GrupaProjektBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation

logout:
    path:    /logout